export const SUBSCRIPTION_PLAN_KEYS = {
  STANDART: 'standart',
  PREMIUM: 'premium',
} as const;

export const SUBSCRIPTION_PLAN_ORDER = [
  SUBSCRIPTION_PLAN_KEYS.STANDART,
  SUBSCRIPTION_PLAN_KEYS.PREMIUM,
] as const;

export const SUBSCRIPTION_PLAN_PRICES = {
  [SUBSCRIPTION_PLAN_KEYS.STANDART]: '$0',
  [SUBSCRIPTION_PLAN_KEYS.PREMIUM]: '0.01 SUI',
} as const;
