export const HEADER_ROUTES = {
  HOME: '/',
  TESTS: '/tests',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
} as const;

export const HEADER_LABELS = {
  BRAND: 'Test flow',
  TESTS: 'Tests',
  LOGIN: 'Login',
  REGISTER: 'Register',
  LOGOUT: 'Logout',
  LANGUAGE_MENU_ARIA: 'Language options',
  USER_MENU_ARIA: 'User menu',
  MAIN_NAV_ARIA: 'Main navigation',
} as const;

export const LANGUAGE_STORAGE_KEY = 'testflow-language';
export const LANGUAGE_CHANGE_EVENT = 'testflow-language-change';

export const LANGUAGE_VALUES = {
  UKR: 'ukr',
  ENG: 'eng',
} as const;

export const LANGUAGE_LABELS = {
  ukr: 'Ukr',
  eng: 'Eng',
} as const;

export const APP_TEXT = {
  eng: {
    header: {
      brand: 'Test flow',
      tests: 'Tests',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      goToProfile: 'Go to profile',
      languageMenuAria: 'Language options',
      userMenuAria: 'User menu',
      mainNavAria: 'Main navigation',
    },
    home: {
      title: 'Create tests easily',
      description: 'A platform for creating and taking tests. Save notes, share knowledge, and test your skills.',
    },
    auth: {
      loginTitle: 'Login',
      registerTitle: 'Register',
      loginDescription: 'Sign in to continue.',
      registerDescription: 'Create your account.',
      noAccount: 'No account yet? Register',
      alreadyAccount: 'Already have an account? Login',
      username: 'Login',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      capsLabel: 'CAPS',
      loading: 'Loading...',
      errors: {
        loginRequired: 'Login and password are required.',
        unableToLogin: 'Unable to login.',
        nameRequired: 'Login is required.',
        emailRequired: 'Email is required.',
        passwordRequired: 'Password is required.',
        confirmRequired: 'Confirm password is required.',
        passwordsMatch: 'Passwords must match.',
        unableToRegister: 'Unable to register.',
      },
      passwordRules: {
        minLength: 'Password must be at least {{min}} characters.',
        uppercase: 'Password must include at least one uppercase letter.',
        lowercase: 'Password must include at least one lowercase letter.',
        number: 'Password must include at least one number.',
      },
    },
    testsCatalog: {
      title: 'Tests',
      loading: 'Loading tests...',
      loadError: 'Unable to load tests. Try again later.',
      empty: 'No tests found.',
      searchLabel: 'Search by Shared Code',
      searchPlaceholder: 'Enter shared code',
      noSearchResults: 'No tests found for this shared code.',
    },
    testCard: {
      public: 'Public',
      private: 'Private',
      noDescription: 'No description yet.',
      code: 'Code',
      noValue: 'N/A',
      timeLimit: 'Time limit: {{minutes}} min',
      noTimeLimit: 'No time limit',
    },
    testSession: {
      testFallbackTitle: 'Test {{id}}',
      questionFallbackTitle: 'Question {{id}}',
      optionFallbackTitle: 'Option {{id}}',
      sharedCode: 'Shared code',
      loading: 'Loading test...',
      loadError: 'Unable to load this test right now.',
      noQuestions: 'No questions available for this test.',
      resultTitle: 'Your result',
      score: 'Score',
      correctAnswers: 'Correct answers',
      incorrectAnswers: 'Incorrect answers',
      timeSpent: 'Time spent: {{seconds}} sec',
      yourAnswer: 'Your answer:',
      correctAnswer: 'Correct answer:',
      points: 'Points:',
      noAnswer: 'No answer',
      notProvided: 'Not provided by backend',
      noOptions: 'No answer options available for this question.',
      validation: 'Answer all questions before submitting.',
      submitting: 'Submitting...',
      submit: 'Submit test',
      backToTests: 'Back to all tests',
      persistSaved: 'Result saved to backend.',
      persistFailed: 'Result calculated, but backend save failed.',
      persistLocalOnly: 'Result calculated locally. No active backend attempt found for this quiz.',
    },
    profile: {
      title: 'Profile',
      name: 'Name',
      email: 'Email',
      noValue: 'N/A',
    },
    api: {
      unexpectedResponse: 'Unexpected server response.',
      requestFailed: 'Request failed.',
      registrationSuccess: 'Registration successful.',
      loginSuccess: 'Login successful.',
    },
  },
  ukr: {
    header: {
      brand: 'Test flow',
      tests: 'Тести',
      login: 'Увійти',
      register: 'Реєстрація',
      logout: 'Вийти',
      goToProfile: 'Перейти в профіль',
      languageMenuAria: 'Параметри мови',
      userMenuAria: 'Меню користувача',
      mainNavAria: 'Головна навігація',
    },
    home: {
      title: 'Створюй тести легко',
      description: 'Платформа для створення та проходження тестів. Зберігай нотатки, ділись знаннями та перевіряй навички.',
    },
    auth: {
      loginTitle: 'Увійти',
      registerTitle: 'Реєстрація',
      loginDescription: 'Увійдіть, щоб продовжити.',
      registerDescription: 'Створіть свій акаунт.',
      noAccount: 'Ще немає акаунта? Зареєструйтесь',
      alreadyAccount: 'Вже маєте акаунт? Увійдіть',
      username: "Логін",
      email: 'Email',
      password: 'Пароль',
      confirmPassword: 'Підтвердьте пароль',
      capsLabel: 'CAPS',
      loading: 'Завантаження...',
      errors: {
        loginRequired: "Логін і пароль обов'язкові.",
        unableToLogin: 'Не вдалося увійти.',
        nameRequired: "Логін обов'язковий.",
        emailRequired: "Email обов'язковий.",
        passwordRequired: "Пароль обов'язковий.",
        confirmRequired: 'Підтвердження пароля обовʼязкове.',
        passwordsMatch: 'Паролі мають співпадати.',
        unableToRegister: 'Не вдалося зареєструватися.',
      },
      passwordRules: {
        minLength: 'Пароль має містити щонайменше {{min}} символів.',
        uppercase: 'Пароль має містити хоча б одну велику літеру.',
        lowercase: 'Пароль має містити хоча б одну малу літеру.',
        number: 'Пароль має містити хоча б одну цифру.',
      },
    },
    testsCatalog: {
      title: 'Тести',
      loading: 'Завантаження тестів...',
      loadError: 'Не вдалося завантажити тести. Спробуйте пізніше.',
      empty: 'Тестів не знайдено.',
      searchLabel: 'Пошук за спільним кодом',
      searchPlaceholder: 'Введіть спільний код',
      noSearchResults: 'За цим кодом тестів не знайдено.',
    },
    testCard: {
      public: 'Публічний',
      private: 'Приватний',
      noDescription: 'Опис поки відсутній.',
      code: 'Код',
      noValue: 'Н/Д',
      timeLimit: 'Ліміт часу: {{minutes}} хв',
      noTimeLimit: 'Без обмеження часу',
    },
    testSession: {
      testFallbackTitle: 'Тест {{id}}',
      questionFallbackTitle: 'Питання {{id}}',
      optionFallbackTitle: 'Варіант {{id}}',
      sharedCode: 'Спільний код',
      loading: 'Завантаження тесту...',
      loadError: 'Не вдалося завантажити цей тест зараз.',
      noQuestions: 'Для цього тесту немає запитань.',
      resultTitle: 'Ваш результат',
      score: 'Бали',
      correctAnswers: 'Правильні відповіді',
      incorrectAnswers: 'Неправильні відповіді',
      timeSpent: 'Витрачено часу: {{seconds}} с',
      yourAnswer: 'Ваша відповідь:',
      correctAnswer: 'Правильна відповідь:',
      points: 'Бали:',
      noAnswer: 'Немає відповіді',
      notProvided: 'Не надано бекендом',
      noOptions: 'Для цього запитання немає варіантів відповіді.',
      validation: 'Відповідайте на всі запитання перед відправкою.',
      submitting: 'Відправлення...',
      submit: 'Відправити тест',
      backToTests: 'Назад до всіх тестів',
      persistSaved: 'Результат збережено на бекенді.',
      persistFailed: 'Результат обчислено, але збереження на бекенді не вдалося.',
      persistLocalOnly: 'Результат обчислено локально. Активної спроби на бекенді для цього тесту не знайдено.',
    },
    profile: {
      title: 'Профіль',
      name: "Ім'я",
      email: 'Email',
      noValue: 'Н/Д',
    },
    api: {
      unexpectedResponse: 'Неочікувана відповідь сервера.',
      requestFailed: 'Помилка запиту.',
      registrationSuccess: 'Реєстрація успішна.',
      loginSuccess: 'Вхід успішний.',
    },
  },
} as const;
